//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select *,
        ///case 
        ///	when DaySupply &gt; 90 then 1
        ///	when DaySupply between 45 and 90 then 2
        ///	when DaySupply &lt; 45 then 3 end as Indicator
        ///from 
        ///(
        ///	select 
        ///	*, 
        ///	case when Data.Sold - Data.Inventory &lt; 0 THEN 0 
        ///	else Data.Sold - Data.Inventory END as OrderQuantity,
        ///	convert(int, (convert(decimal(10,2),Data.Inventory) / convert(decimal(10,2),Data.Sold) * 90.00)) DaySupply
        ///	from
        ///	(
        ///		   select v.VehicleMake, v.VehicleModel, count(1) Sold,
        ///		   (
        ///				  select count(1) 
        ///				  from dmsd.VehicleInventory  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ForecastQuery {
            get {
                return ResourceManager.GetString("ForecastQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 
        ///	datepart(m,DmsSoldDate) Month ,count(0) as Quantity 
        ///from dmsd.Deals d
        ///join dmsd.Vehicles v on v.LoopVehicleId = d.LoopVehicleId
        ///where 
        ///	v.VehicleMake = @VehicleMake
        ///and
        ///	v.VehicleModel = @VehicleModel
        ///group by datepart(m,DmsSoldDate).
        /// </summary>
        internal static string SalesHistoryQuery {
            get {
                return ResourceManager.GetString("SalesHistoryQuery", resourceCulture);
            }
        }
    }
}
